version: 2

p2pd_steps: &p2pd_steps
  steps:
    - checkout
    - restore_cache:
        keys:
          - cache-v0-{{ arch }}-p2pd-{{ checksum "./.circleci/install_p2pd.sh" }}
    - run:
        name: build libp2p daemon
        command: ./.circleci/install_p2pd.sh
    - save_cache:
        paths:
          - ~/.p2pd
        key: cache-v0-{{ arch }}-p2pd-{{ checksum "./.circleci/install_p2pd.sh" }}
    - restore_cache:
        keys:
          - cache-v0-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install deps
        command: pip install --user tox codecov
    - run:
        name: run tests
        command: |
          command -v p2pd
          ~/.local/bin/tox
    - run:
        name: update codecov
        command: ~/.local/bin/codecov
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
        key: cache-v0-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  lint:
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: lint
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-v0-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
      - run:
          command: |
            pip install --user tox codecov
            ~/.local/bin/tox
      - save_cache:
          paths:
            - .tox
            - ~/.cache/pip
            - ~/.local
          key: cache-v0-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
  py37-test:
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37
    <<: *p2pd_steps
  deploy:  # Ref: https://circleci.com/blog/continuously-deploying-python-packages-to-pypi-with-circleci/
    docker:
      - image: circleci/python:3.7
      - steps:
        - checkout
        # TODO: Verify if the tag matches the version in `setup.py`.
        - run:
            name: init .pypirc
            command: |
              echo -e "[pypi]" >> ~/.pypirc
              echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
              echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
        - run:
            name: create packages
            command: make package
        - run:
            name: install twine
            command: pip install --user twine
        - run:
            name: upload to pypi
            command: twine upload dist/* --verbose
        - run:
            name: pip install from PyPI
            command: |
              pip install --user p2pclient
              # TODO: Verify if the version matches the tag.


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - lint
      - py37-test
      - deploy:
          requires:
            - lint
            - py37-test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
